#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  ftp:

services:
  vsftpd:
    container_name: vsftpd
    image: fauria/vsftpd
    restart: always
    environment:
      - FTP_USER=ftp
      - FTP_PASS=mypass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./data:/home/vsftpd
    networks:
      - ftp
